exports.jobs = [
  {
    title: "Senior Full Stack Developer",
    department: "Engineering",
    location: "Bangalore / Remote",
    type: "Full-time",
    experience: "3-5 years",
    description: "Build scalable fintech solutions using React, Node.js, and blockchain technologies.",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
  },
  {
    title: "Product Manager",
    department: "Product",
    location: "Mumbai / Remote",
    type: "Full-time",
    experience: "4-6 years",
    description: "Drive product strategy and roadmap for our micro-investing platform.",
    skills: ["Product Strategy", "User Research", "Analytics", "Fintech", "Agile"],
  },
  {
    title: "UI/UX Designer",
    department: "Design",
    location: "Delhi / Remote",
    type: "Full-time",
    experience: "2-4 years",
    description: "Create intuitive and beautiful user experiences for financial products.",
    skills: ["Figma", "User Research", "Prototyping", "Design Systems", "Mobile Design"],
  },
  {
    title: "DevOps Engineer",
    department: "Engineering",
    location: "Bangalore / Remote",
    type: "Full-time",
    experience: "3-5 years",
    description: "Manage infrastructure and deployment pipelines for high-availability systems.",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD", "Monitoring"],
  },
  {
    title: "Data Scientist",
    department: "AI/ML",
    location: "Hyderabad / Remote",
    type: "Full-time",
    experience: "2-4 years",
    description: "Develop AI models for portfolio optimization and risk management.",
    skills: ["Python", "Machine Learning", "TensorFlow", "Statistics", "Finance"],
  },
  {
    title: "Marketing Manager",
    department: "Marketing",
    location: "Mumbai / Remote",
    type: "Full-time",
    experience: "3-5 years",
    description: "Lead digital marketing campaigns and user acquisition strategies.",
    skills: ["Digital Marketing", "Growth Hacking", "Analytics", "Content Strategy", "SEO"],
  },
]

exports.perks = [
  "🏠 Remote-first culture with flexible working hours",
  "💰 Competitive salary with equity participation",
  "🏥 Premium health insurance for you and family",
  "📚 ₹50,000 annual learning and development budget",
  "🌴 Unlimited paid time off policy",
  "💻 Latest MacBook Pro and home office setup",
  "🍕 Monthly team dinners and quarterly offsites",
  "🚀 Opportunity to shape the future of fintech in India",
]
